/**:
  ros__parameters:
    PID_deadband: 0.05
    target_timeout: 5.0

    descent_kp_pid: 1.0
    descent_ki_pid: 0.0
    descent_kd_pid: 0.0
    descent_max_velocity: 3.0
    slew_acc: 0.9

    land_zone_z: 1.5
    descent_vel: 0.3

    vff_timeout: 0.2

    yaw_kp: 0.2
    yawrate_max: 0.5
    yaw_gate_deg: 8.0
    yaw_gate_delay_s: 0.5
    yaw_switch_r: 0.5