/**:
  ros__parameters:
    debug: false
    debug_csv_path: "kalman_logs/"

    topics.input_target_pose: "/Aruco/target_pose_FRD"
    topics.reset_command: "/Aruco/target_state"
    topics.vehicle_odometry: "/fmu/out/vehicle_odometry"
    topics.vehicle_local_position: "/fmu/out/vehicle_local_position_v1"
    topics.relative_position_raw: "/KF/target_pose_NED"
    topics.relative_position_predicted: "/KF/target_pose_est_NED"
    topics.relative_velocity: "/KF/target_velocity_est_NED"
    topics.covariance: "/KF/target_covariance_NE"
    topics.process_noise: "/KF/process_noise"

    frame_id: "map"

    # =========================
    # Process noise Q
    # độ tin vào mô hình dự đoán
    # Gia toc bat dinh cua target
    # Tang q_acc -> Kalman bam measurement nhanh hon nhung co the nhieu hon
    # Giam q_acc -> output muot hon nhung de tre pha hon
    # =========================
    q_acc_x: 0.2
    q_acc_y: 0.2
    q_acc_z: 0.02

    # =========================
    # Measurement noise R co ban
    # độ tin vào measurement camera
    # Day la phuong sai cua phep do position sau transform camera -> world
    # Gia tri cang lon thi Kalman cang it tin camera
    # =========================
    r_pos_x: 0.008
    r_pos_y: 0.008
    r_pos_z: 0.0041

    dynamic_r.enable: false
    dynamic_r.near_range_m: 0.7
    dynamic_r.near_noise_gain: 0.08
    dynamic_r.max_extra_r_xy: 0.20
    dynamic_r.min_range_m: 0.1

    transform.mount_mode: "belly_fixed_camera"
    transform.camera_offset_x: 0.2
    transform.camera_offset_y: 0.0
    transform.camera_offset_z: -0.12